Many tweaks, better argument handling

diff --git a/eos-tech-support/eos-windows-uninstall b/eos-tech-support/eos-windows-uninstall
--- a/eos-tech-support/eos-windows-uninstall
+++ b/eos-tech-support/eos-windows-uninstall
@@ -1,22 +1,68 @@
-#!/bin/bash -e
+#!/bin/bash
 # Copyright (C) 2016 Endless Mobile, Inc.
 # Licensed under the GPLv2
+set -e
 set -o pipefail
 
-#Usage: eos-windows-uninstall [device]
-#Uninstalls grub and restores the normal Windows boot setup
-#For MBR bootracks, bootrack.img is saved by the installer
-#On EFI systems, we use efibootmgr to get rid of grub
+ARGS=$(getopt -o gnh -l "gap,no-act,help" -n "$0" -- "$@")
+eval set -- "$ARGS"
+
+usage() {
+    cat <<EOF
+Usage:
+   $0 [--no-act] DEVICE
+
+Uninstalls GRUB from an Endless OS dual-boot machine, restoring the normal
+Windows boot setup.
+
+Arguments:
+    DEVICE        Device path (e.g. '/dev/sda')
+
+Options:
+    -g,--gap      On MBR drives, reinstate the sectors between the MBR and the
+                  first partition. (The second stage of GRUB is written here.)
+                  You may need this if GRUB has overwritten something important.
+    -n,--no-act   Don't actually make any changes to DEVICE
+EOF
+}
+
+while true; do
+    case "$1" in
+        -g|--gap)
+            shift
+            GAP="true"
+            ;;
+        -n|--no-act)
+            shift
+            NO_ACT="true"
+            ;;
+        -h|--help)
+            usage
+            exit 0
+            ;;
+        --)
+            shift
+            break
+            ;;
+    esac
+done
+
+#arguments checking
+if [ $# -lt 1 ]; then
+  echo "Missing DEVICE" >&2
+  usage >&2
+  exit 1
+fi
+dev="$(realpath $1)"
 
 #Windows partition labels
 WIN_GUID="EBD0A0A2-B9E5-4433-87C0-68B6B72699C7"
-WIN_MBR="type=7"
-LINUX_MBR="type=83" #for testing only
+WIN_MBR="7"
 
 #If we have mounted a partition, unmount before exiting
 #Remove the temp files we created
 cleanup() {
-    if ! [ -z $mountpoint ] && ! [ -z $found ]; then
+    if ! [ -z "$mountpoint" ] && ! [ -z "$found" ]; then
         udisksctl unmount -b "$part" --no-user-interaction
     fi
     rm -rf /tmp/eos-uninstall.*
@@ -25,16 +71,9 @@ trap cleanup EXIT
 
 #make sure we're root
 if [ "$(id -u)" != "0" ]; then
-    echo "$0 must be run as root."
+    echo "$0 must be run as root." >&2
     exit 1
 fi
-
-#arguments checking
-if [ $# -lt 1 ]; then
-  echo "Usage: $0 <EOS+WINDOWS DEVICE>" >&2
-  exit 1
-fi
-dev="$(realpath $1)"
 
 #Read the partition table off of the device.
 #Save partition label in a temporary file in case we need to restore it
@@ -44,30 +83,30 @@ dev="$(realpath $1)"
 #    3) is not mounted
 table="$(mktemp -t eos-uninstall.XXXXXX)";
 if ! [ -b "$dev" ]; then
-    echo "$dev is not a block device."
+    echo "$dev is not a block device." >&2
     exit 1
-elif ! sfdisk --dump $dev > $table; then
-    echo "Partition table could not be read on $dev"
+elif ! sfdisk --dump "$dev" > "$table"; then
+    echo "Partition table could not be read on $dev" >&2
     exit 1
 elif grep -qs "$dev" /proc/mounts; then
-    echo "$dev is mounted. Please unmount it and try again."
+    echo "$dev is mounted. Please unmount it and try again." >&2
     exit 1
 fi
 
 #Display the partition table
 echo "Partition table found on device."
-cat $table
+cat "$table"
 
 #Iterate over all Windows partitions on the device and mount them
-#Fail if we find no partitions that match the windows signature
+#Fail if we find no partitions that match the Windows signature
 #Stop when we find endless/endless.img
 endless_img_path=""; win_parts="$(mktemp -t eos-uninstall.XXXXXX)"
-echo "Searching for windows partitions"
+echo "Searching for Windows partitions"
 
-#Save windows partitions to a temporary file
+#Save Windows partitions to a temporary file
 #Iterate over them and mount each, then grab the mount point
 #Exit if we don't find any Windows partitions
-if grep "$WIN_MBR\|$LINUX_MBR" $table | cut -f1 -d' ' > $win_parts; then
+if grep -i "type=$WIN_MBR\>\|type=$WIN_GUID" "$table" | cut -f1 -d' ' > $win_parts; then
     while read part; do
         echo "Mounting partition: $part"
         udisksctl mount -o ro -b "$part" --no-user-interaction
@@ -80,12 +119,12 @@ if grep "$WIN_MBR\|$LINUX_MBR" $table | cut -f1 -d' ' > $win_parts; then
         fi
         udisksctl unmount -b "$part" --no-user-interaction
     done < $win_parts
-    if [ -z $found ]; then
-        echo "endless/endless.img not found."
+    if [ -z "$found" ]; then
+        echo "endless/endless.img not found." >&2
         exit 1
     fi
 else
-    echo "No windows partitions found on device."
+    echo "No Windows partitions found on device." >&2
     exit 1
 fi
 
@@ -97,23 +136,26 @@ echo "label type is $label_type"
 #Check that
 #    1) bootrack.img exists alongside endless.img
 #    2) The partition table on bootrack.img matches the one on the device
-#    3) The size of boottrack.img matches the space before partition 1 (1048576 bytes)
+#    3) The size of boottrack.img matches the space before partition 1 (typically 1MiB)
 #Write boottrack.img to the HDD, skipping the partition table.
 if [ "$label_type" = "dos" ]; then
     boottrack_path="${mountpoint}/endless/boottrack.img"
 
-    #Get the start of the first partition from sfdisk output
-    start="$(awk -F':|,| ' '/start=/ { gsub(/ /, "", $0);
-                gsub(/start=/, "", $0);
-                print $2 } ' "$table" | head -n 1)"
-    #512 bytes per sector
-    start=$(($start*512))
+    # Get the start of the first partition from sfdisk output
+    # Note that sfdisk --dump lists partitions in numerical order, not on-disk order.
+    # Units are sectors of 512 bytes.
+    start="$(python -c 'import re, sys; print(512 * min(map(int,
+        re.findall(r"start=\s*(\d+)", open(sys.argv[1]).read()))))' "$table")"
 
     if ! [ -f "$boottrack_path" ]; then
-        echo "endless/bootrack.img not found. Aborting."
+        echo "$boottrack_path not found. Aborting." >&2
         exit 1
-    elif [ "$(stat $boottrack_path --format=%s)" != "$start" ]; then
-        echo "boottrack.img is the wrong size. Aborting."
+    fi
+
+    boottrack_size="$(stat $boottrack_path --format=%s)"
+
+    if [ "$boottrack_size" != "$start" ]; then
+        echo "$boottrack_path is $boottrack_size bytes; expected $start. Aborting." >&2
         exit 1
     fi
 
@@ -124,24 +166,35 @@ if [ "$label_type" = "dos" ]; then
                 if ($3 ~ /start=/) {
                     $1 = ""; $2 = "";
                 }
-            print
+                print
             }
         }'
     }
     boottrack_table="$(mktemp -t eos-uninstall.XXXXXX)"
     disk_table="$(mktemp -t eos-uninstall.XXXXXX)"
-    sfdisk -d $boottrack_path | remove_table_ids > $boottrack_table
-    cat $table | remove_table_ids > $disk_table
+    sfdisk -d "$boottrack_path" | remove_table_ids > "$boottrack_table"
+    cat "$table" | remove_table_ids > "$disk_table"
 
-    if diff -q "$boottrack_table" "$disk_table"; then
-        echo "Writing boottrack.img to $dev"
-        dd if=$boottrack_path of=$dev bs=1 count=440
-        dd if=$boottrack_path of=$dev bs=512 skip=1 seek=1
+    if diff -u "$boottrack_table" "$disk_table"; then
+        if [ -z "$NO_ACT" ]; then
+            echo "Reinstating MBR on $dev from $boottrack_path"
+            dd if="$boottrack_path" of="$dev" bs=1 count=440
+            udevadm settle
+
+            if [ "$GAP" == "true" ]; then
+                echo "Reinstating boot gap on $dev from $boottrack_path"
+                dd if="$boottrack_path" of="$dev" bs=512 skip=1 seek=1
+                udevadm settle
+            fi
+        else
+            echo "(Would write boottrack.img to $dev, but you specified --no-act)"
+        fi
     else
-        echo "Partition table on boottrack.img differs from partition table on $dev. Aborting"
+        echo "Partition table on $boottrack_path differs from that on $dev. Aborting" >&2
         exit 1
     fi
 else
-    echo "UEFI is not supported yet. Sorry about that."
+    echo "UEFI dual-boot systems are not yet supported by this tool." >&2
+    echo "You can use efibootmgr by hand to change the boot configuration." >&2
     exit 1
 fi
