eos-write-installer: Exit if no storage devices are found
https://phabricator.endlessm.com/T35167

diff --git a/eos-tech-support/eos-write-installer b/eos-tech-support/eos-write-installer
--- a/eos-tech-support/eos-write-installer
+++ b/eos-tech-support/eos-write-installer
@@ -99,6 +99,11 @@ function choose_device() {
         fi
     done <<< "$all_devices"
 
+    if [ ${#device_labels[@]} -eq 0 ]; then
+        echo "No removable storage devices are available... aborting!" >&2
+        exit 1
+    fi
+
     echo "Choose a removable storage device to use:" >&2
 
     local PS3="Choose a device: "
