eos-write-installer: Use .sha256 if .asc is missing
Since Endless OS 4, eos-installer has supported verifying the image
against a .sha256 file containing a SHA256 checksum of the image if no
detached GPG signature (.asc) is present. This is so that custom images
built by third parties, who do not have our private image signing key,
can be installed with eos-installer.

However, eos-write-installer still required that the OS image have a
.asc GPG signature, and so would refuse to write an installer for a
custom-built OS image that has only a .sha256 checksum.

Check for both, using the .asc for preference, and fail only if neither
is present.

https://phabricator.endlessm.com/T35362

diff --git a/eos-tech-support/eos-write-installer b/eos-tech-support/eos-write-installer
--- a/eos-tech-support/eos-write-installer
+++ b/eos-tech-support/eos-write-installer
@@ -50,6 +50,7 @@ EOF
 
 INSTALLER_IMAGE=
 OS_IMAGE=
+OS_IMAGE_SIGNATURE=
 FETCH_LATEST=
 UPDATE_INSTALLER=
 DEVICE=
@@ -63,6 +64,19 @@ EOSIMAGES_WAS_AUTO_MOUNTED=
 function check_exists() {
     if [ ! -f "$1" ]; then
         echo "Error: $1 does not exist or is not a file" >&2
+        exit 1
+    fi
+}
+
+function find_os_image_signature() {
+    local asc="${OS_IMAGE:?}.asc"
+    local sha256="$OS_IMAGE.sha256"
+    if [ -f "$asc" ]; then
+        OS_IMAGE_SIGNATURE="$asc"
+    elif [ -f "$sha256" ]; then
+        OS_IMAGE_SIGNATURE="$sha256"
+    else
+        echo "Error: Neither $asc (GPG signature) nor $sha256 (sha256sum file) exist" >&2
         exit 1
     fi
 }
@@ -133,7 +147,7 @@ function print_device_summary() {
     local eosimages_df
     local other_os_images
     eosimages_df=$(df -h . | tail -1 | tr -s ' ' | cut -d ' ' -f4)
-    other_os_images=$(find . -type f -not -name '*.asc')
+    other_os_images=$(find . -type f -not '(' -name '*.asc' -o -name '*.sha256' ')' )
     echo "$DEVICE has $eosimages_df remaining and contains the following OS images:" >&2
     while read -r other_os_image; do
         local other_os_image_name
@@ -160,7 +174,7 @@ while true; do
             shift
             OS_IMAGE="$1"
             check_exists "$OS_IMAGE"
-            check_exists "$OS_IMAGE.asc"
+            find_os_image_signature
             shift
             ;;
         -l|--latest)
@@ -244,6 +258,7 @@ if [ -n "$FETCH_LATEST" ]; then
 
     if [ -z "$OS_IMAGE" ]; then
         OS_IMAGE=$($EOS_DOWNLOAD_IMAGE --product eos)
+        find_os_image_signature
     fi
 fi
 
@@ -338,7 +353,7 @@ if [ -f "$OS_IMAGE" ]; then
     echo "Adding $OS_IMAGE to eosimages on $DEVICE..." >&2
 
     # Write image and its signature
-    cp "$OS_IMAGE.asc" "$EOSIMAGES_MOUNTPOINT"/
+    cp "$OS_IMAGE_SIGNATURE" "$EOSIMAGES_MOUNTPOINT"/
     pv "$OS_IMAGE" > "$EOSIMAGES_MOUNTPOINT"/"$(basename "$OS_IMAGE")"
 fi
 
