eos-list-users: continue if mounting a partition fails
If a partition can't be mounted, it might be due to a bug, or it might
be something wrong with that partition. Maybe the user has a hard drive
with a partition of type "basic data" but without a filesystem on it? In
particular, this happens when running this script from a combined USB,
because the physical eoslive partition (eg /dev/sdb1) cannot be mounted
directly. It's better to continue and list users on other partitions
even if we show an error.

https://phabricator.endlessm.com/T17560

diff --git a/eos-tech-support/eos-list-users b/eos-tech-support/eos-list-users
--- a/eos-tech-support/eos-list-users
+++ b/eos-tech-support/eos-list-users
@@ -31,7 +31,10 @@ list_users() {
     local DEVICE=$1
     local PHYSICAL_DEVICE=$2
 
-    mount $DEVICE $MOUNT
+    if ! mount $DEVICE $MOUNT; then
+        echo "Can't list users on $PHYSICAL_DEVICE" >&2
+        return
+    fi
 
     # FIXME A more robust approach would be the following:
     # - read /usr/etc/login.defs and extract UID_MIN
@@ -46,7 +49,11 @@ list_users() {
 list_dualboot_users() {
     local PHYSICAL_DEVICE=${1:?}
 
-    mount $PHYSICAL_DEVICE $MOUNT
+    if ! mount $PHYSICAL_DEVICE $MOUNT; then
+        echo "Can't list users on $PHYSICAL_DEVICE" >&2
+        return
+    fi
+
     local ENDLESS_IMG="$MOUNT/endless/endless.img"
 
     if [ -e "$ENDLESS_IMG" ] && [ ! -e "$MOUNT/endless/live" ]; then
