eos-reset-password: support dual-boot installations
https://phabricator.endlessm.com/T14302

diff --git a/eos-tech-support/eos-reset-password b/eos-tech-support/eos-reset-password
--- a/eos-tech-support/eos-reset-password
+++ b/eos-tech-support/eos-reset-password
@@ -31,14 +31,49 @@ else
 fi
 
 MOUNT=`mktemp -d`
+LOOPBACK=
 
 cleanup() {
     set +e
-    umount $MOUNT
-    rmdir $MOUNT
+
+    umount "$MOUNT"
+
+    if [ -n "$LOOPBACK" ]; then
+        losetup -d "$LOOPBACK"
+        udevadm settle
+
+        umount "$MOUNT"
+    fi
+
+    rmdir "$MOUNT"
 }
 trap cleanup EXIT
 
 mount $DEVICE $MOUNT
+
+# Check if it's a Windows partition with a dual-boot Endless OS image
+LABEL=$(lsblk -o LABEL --raw --nodeps --noheadings "$DEVICE")
+ENDLESS_IMG="$MOUNT/endless/endless.img"
+if [ "$LABEL" != "ostree" ] && [ -e "$ENDLESS_IMG" ]; then
+    if [ -e "$MOUNT/endless/live" ]; then
+        echo "$DEVICE is a read-only live USB; refusing to change passwords" >&2
+        exit 1
+    fi
+
+    # Time for a loopback mount!
+    LOOPBACK=$(losetup --find --show "$ENDLESS_IMG")
+    partprobe "$LOOPBACK"
+
+    # Find the ostree partition
+    DEVICE=$(lsblk --raw --paths -o LABEL,NAME "$LOOPBACK" |
+             awk '/^ostree / { print $2 }')
+    if [ -z "$DEVICE" ]; then
+        echo "Cannot find Endless OS partition in $ENDLESS_IMG" >&2
+        exit 1
+    fi
+
+    mount "$DEVICE" "$MOUNT"
+fi
+
 CURRENT=$(ostree admin --sysroot=$MOUNT --print-current-dir)
 sed -i "s/$USERNAME:[^:]*:[^:]*:/$USERNAME::$DATE:/" $CURRENT/etc/shadow
