eos-fix-mbr-swap-removal: Improve logging
Save a log file in /tmp and tell the user its path every time the
program exits, so they can upload it in case further help is needed.

https://phabricator.endlessm.com/T24493

diff --git a/eos-tech-support/eos-fix-mbr-swap-removal b/eos-tech-support/eos-fix-mbr-swap-removal
--- a/eos-tech-support/eos-fix-mbr-swap-removal
+++ b/eos-tech-support/eos-fix-mbr-swap-removal
@@ -21,8 +21,27 @@ if [[ ${#} -ne 1 ]] ; then
     exit 1
 fi
 
-PARTITIONS_FILE=$(mktemp --tmpdir $(basename ${0})-XXXXXXXXXX)
-chmod 644 ${PARTITIONS_FILE}
+WORKDIR=$(mktemp --directory --tmpdir $(basename ${0})-XXXXXXXXXX)
+chmod 755 ${WORKDIR}
+PARTITIONS_FILE="${WORKDIR}/partitions.txt"
+LOG_FILE="${WORKDIR}/$(basename ${0})-logs-$(date --iso-8601=seconds).txt"
+
+print_log() {
+    echo "${1}" >> ${LOG_FILE}
+}
+
+print_log_with_partitions() {
+    print_log "${1}"
+    cat ${PARTITIONS_FILE} >> ${LOG_FILE}
+}
+
+exit_error() {
+    print_log_with_partitions "Error: ${1}"
+    rm ${PARTITIONS_FILE}
+    echo "Error: ${1}" > /dev/stderr
+    echo "Logs saved to ${LOG_FILE}."
+    exit ${2}
+}
 
 root_disk=${1}
 sfdisk -d ${root_disk} > ${PARTITIONS_FILE}
@@ -30,24 +49,21 @@ sfdisk -d ${root_disk} > ${PARTITIONS_FILE}
 # Check this is a MBR partiton table
 label_type=$(sed -n -e 's/^label: [ ]*\(.*\)$/\1/p' ${PARTITIONS_FILE})
 if [[ ${label_type} != "dos" ]] ; then
-    echo "Error: This is not a MBR partition table"
-    echo
-    cat ${PARTITIONS_FILE}
-    exit 2
+    exit_error "Error: This is not a MBR partition table." 2
 fi
 
 # Check that the partition starting at 144585 is a bootable Linux partition
 type83_bootable=$(sed -n -e 's/^.*start=[ ]*144585,.*\(type=83, bootable\).*$/\1/p' ${PARTITIONS_FILE})
 if [[ ${type83_bootable} != "type=83, bootable" ]] ; then
-    echo "Error: The partition starting at 144585 is not a bootable Linux partition"
-    echo
-    cat ${PARTITIONS_FILE}
-    exit 3
+    exit_error "Error: The partition starting at 144585 is not a bootable Linux partition." 3
 fi
 
 # Change the starting of the bootable Linux partition from 144585 to 131072
+print_log_with_partitions "Original partition table:"
 sed -i -e 's/\(start=[ ]*\)144585\(.*\), size=[ ]*[^,]*/\1131072\2/' ${PARTITIONS_FILE}
-sfdisk --force --no-reread ${root_disk} < ${PARTITIONS_FILE}
+print_log_with_partitions "New partition table:"
+print_log "$(sfdisk --force --no-reread ${root_disk} < ${PARTITIONS_FILE} 2>&1)"
 rm ${PARTITIONS_FILE}
 udevadm settle
-lsblk -f ${root_disk}
+print_log "$(lsblk -f ${root_disk})"
+echo "Partition table fixed, logs saved to ${LOG_FILE}."
