eos-write-live-image: add support to expand image
Add two parameters to expand to the disk size and to a set size.

https://phabricator.endlessm.com/T26120

diff --git a/eos-tech-support/eos-write-live-image b/eos-tech-support/eos-write-live-image
--- a/eos-tech-support/eos-write-live-image
+++ b/eos-tech-support/eos-write-live-image
@@ -19,7 +19,7 @@ if [ ! -f "$EOS_DOWNLOAD_IMAGE" ]; then
     EOS_DOWNLOAD_IMAGE='eos-download-image'
 fi
 
-ARGS=$(getopt -o o:x:lp:r:nmwL:fh \
+ARGS=$(getopt -o o:x:lp:r:nms:wL:fh \
     -l os-image: \
     -l windows-tool: \
     -l latest \
@@ -27,6 +27,8 @@ ARGS=$(getopt -o o:x:lp:r:nmwL:fh \
     -l product: \
     -l ntfs \
     -l mbr \
+    -l size: \
+    -l fill \
     -l writable \
     -l label: \
     -l force \
@@ -37,6 +39,8 @@ eval set -- "$ARGS"
 
 NTFS=
 MBR=
+EXPAND=
+SIZE=
 WRITABLE=
 FORCE=
 PERSONALITY=base
@@ -64,6 +68,8 @@ Options:
     -p, --personality        Fetch a different personality (default: $PERSONALITY)
     -r, --product            Fetch a different product (default: $PRODUCT)
     -L, --label LABEL        Autorun.inf label (default: Endless OS)
+    -s, --size SIZE          Expand the image to desired size in bytes
+        --fill               Expand the image to fill the target disk
     -w, --writable           Allow image to be modified when run (which
                              prevents installing it later)
     -f, --force              don't ask to proceed before writing
@@ -80,6 +86,13 @@ function check_exists() {
     if [ ! -f "$1" ]; then
         echo "$2 $1 does not exist or is not a file" >&2
         exit 1
+    fi
+}
+
+function cleanup() {
+    udisks_unmount "$DEVICE_IMAGES"
+    if [ ! "$MBR" ]; then
+        udisks_unmount "$DEVICE_EFI"
     fi
 }
 
@@ -138,6 +151,16 @@ while true; do
         -w|--writable)
             shift
             WRITABLE=true
+            ;;
+        --fill)
+            shift
+            EXPAND=true
+            ;;
+        -s|--size)
+            shift
+            EXPAND=true
+            SIZE="$1"
+            shift
             ;;
         -L|--label)
             shift
@@ -209,6 +232,10 @@ else
     dependencies[$MKFS_IMAGES]='exfat-utils'
 fi
 
+if [ "$EXPAND" ]; then
+    dependencies[truncate]='coreutils'
+fi
+
 for command in "${!dependencies[@]}"; do
     if ! which "$command" >/dev/null 2>&1; then
         echo "$command is not installed... aborting!" >&2
@@ -231,10 +258,21 @@ if [ -z "$FETCH_LATEST" ]; then
     fi
 fi
 
+if [ -n "$SIZE" ]; then
+    SIZE_DESC=$SIZE
+else
+    if [ -n "$EXPAND" ]; then
+        SIZE_DESC="fill disk"
+    else
+        SIZE_DESC="n/a"
+    fi
+fi
+
 echo "Summary:"
 echo
 echo "       Endless OS image: ${OS_IMAGE:-latest $PRODUCT $PERSONALITY image}"
 echo "  Installer for Windows: ${WINDOWS_TOOL:-latest release}"
+echo "      Image target size: ${SIZE_DESC}"
 echo "                 Target: ${OUTPUT}"
 echo
 
@@ -389,13 +427,40 @@ fi
 
 "$EOS_WRITE_IMAGE" "$OS_IMAGE" "-" > "${DIR_IMAGES_ENDLESS}/endless.img"
 
+if [ "$EXPAND" ]; then
+    IMAGE_BYTES=$(du -b "${DIR_IMAGES_ENDLESS}/endless.img" | cut -f1)
+    FREE_SPACE_BYTES=$(df -P -B1 "$DIR_IMAGES_ENDLESS" | awk 'NR==2 {print $4}')
+
+    if [ -n "$SIZE" ]; then
+        if [ $SIZE -lt $IMAGE_BYTES ]; then
+            echo "Cannot expand the image to $SIZE bytes, minimum size is $IMAGE_BYTES bytes" >&2
+            cleanup
+            exit 1
+        fi
+
+        # Expand the image to the provided size
+        EXTRA_BYTES=$(($SIZE - $IMAGE_BYTES))
+
+        if [ $EXTRA_BYTES -gt $FREE_SPACE_BYTES ]; then
+            echo "Cannot expand the image to $SIZE bytes, only $FREE_SPACE_BYTES bytes available" >&2
+            cleanup
+            exit 1
+        fi
+    else
+        # Expand the image to take all the space on the drive
+        SIZE=$(($IMAGE_BYTES + $FREE_SPACE_BYTES))
+    fi
+
+    if [ $SIZE -gt $IMAGE_BYTES ]; then
+        echo "Expanding the image from $IMAGE_BYTES to $SIZE bytes"
+        truncate --size "$SIZE" "${DIR_IMAGES_ENDLESS}/endless.img"
+    fi
+fi
+
 echo
 echo "Finalizing"
 
-udisks_unmount "$DEVICE_IMAGES"
-if [ ! "$MBR" ]; then
-    udisks_unmount "$DEVICE_EFI"
-fi
+cleanup
 
 if [ "$MBR" ]; then
     # Bootstrap code, which will jump to sector 1
