write-live-image: print a summary of options
This moves it above the "are you sure?" check -- it seems polite to
describe exactly what will be done before asking for confirmation.

Similarly, it seems clearer to check --latest | (--windows-tool &
--os-image) before asking for confirmation.

diff --git a/eos-tech-support/eos-write-live-image b/eos-tech-support/eos-write-live-image
--- a/eos-tech-support/eos-write-live-image
+++ b/eos-tech-support/eos-write-live-image
@@ -221,6 +221,21 @@ for command in "${!dependencies[@]}"; do
     fi
 done
 
+if [ -z "$FETCH_LATEST" ]; then
+    if [ -z "$WINDOWS_TOOL" ] || [ -z "$OS_IMAGE" ]; then
+        echo "--os-image and --windows-tool are required if --latest is not specified" >&2
+        usage >&2
+        exit 2
+    fi
+fi
+
+echo "Summary:"
+echo
+echo "       Endless OS image: ${OS_IMAGE:-latest $PRODUCT $PERSONALITY image}"
+echo "  Installer for Windows: ${WINDOWS_TOOL:-latest release}"
+echo "                 Target: ${OUTPUT}"
+echo
+
 if [ "$ISO" ]; then
     if [ -f "$OUTPUT" ] && [ ! "$FORCE" ]; then
         echo "$OUTPUT already exists... aborting!" >&2
@@ -252,14 +267,6 @@ else
         if [[ ! "$response" =~ ^(yes|y)$ ]]; then
             exit 1
         fi
-    fi
-fi
-
-if [ -z "$FETCH_LATEST" ]; then
-    if [ -z "$WINDOWS_TOOL" ] || [ -z "$OS_IMAGE" ]; then
-        echo "--os-image and --windows-tool are required if --latest is not specified" >&2
-        usage >&2
-        exit 2
     fi
 fi
 
